CREATE TABLE bucket (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   external_id UUID NOT NULL,
   position DOUBLE PRECISION NOT NULL,
   name VARCHAR(255),
   CONSTRAINT pk_bucket PRIMARY KEY (id)
);
ALTER TABLE bucket ADD CONSTRAINT uc_bucket_external UNIQUE (external_id);

CREATE TABLE task (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   external_id UUID NOT NULL,
   position DOUBLE PRECISION NOT NULL,
   name VARCHAR(255),
   bucket_id BIGINT,
   CONSTRAINT pk_task PRIMARY KEY (id)
);
ALTER TABLE task ADD CONSTRAINT uc_task_external UNIQUE (external_id);
ALTER TABLE task ADD CONSTRAINT FK_TASK_ON_BUCKET FOREIGN KEY (bucket_id) REFERENCES bucket (id);

INSERT INTO bucket(external_id, position, name) values
('3731c747-ea27-42e5-a52b-1dfbfa9617db', 200.987, 'SECOND-BUCKET'),
('6d9db741-ef57-4d5a-ac0f-34f68fb0ab5e', 100.15, 'FIRST-BUCKET');
